### ISSUE TITLE
Terdapat Masalah ketika Buka Halaman Utama

### ISSUE THREAD

**Issue by Ariska138** [MuhHannn/portal-siswa-by-hanan#1]
- [x] Ketika buka halaman utama. muncul Error
```
Failed to compile
./src/styles/login.css
Global CSS cannot be imported from files other than your Custom <App>. Due to the Global nature of stylesheets, and to avoid conflicts, Please move all first-party global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://nextjs.org/docs/messages/css-global
Location: src\pages\login.js
```
jika css digunakan di halaman yg spesifik. mana penamaannya harus dengan `*.module.css`. contoh `import styles from '@/styles/login.module.css';`

- [x]  jangan memanggil fuction dari luar yg belum diimportkan. contoh
`${dmSans.className}`
sehingga dapat menyebabkan error.

- [x] ketika buka halaman registration. muncul error pada css
```
Failed to compile
./src/styles/registration.css
Global CSS cannot be imported from files other than your Custom <App>. Due to the Global nature of stylesheets, and to avoid conflicts, Please move all first-party global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://nextjs.org/docs/messages/css-global
Location: src\pages\registration.js
```
sebaiknya penamaan menggunakan `*.module.css` seperti pada login diatas

**Comment by MuhHannn** [comment]
@Ariska138 sudah selesai
![contoh](https://github.com/MuhHannn/portal-siswa-by-hanan/assets/114051587/95e76eb0-f9e2-415d-983d-c4807afa987f)

**Comment by Ariska138** [comment]
Mantap
